# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.nonTransitiveRClass=true
android.overridePathCheck=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.incremental=false
kotlin.incremental.android=false
ksp.incremental=false
kotlin.compiler.execution.strategy=in-process
